### ISSUE TITLE
Pony Circle cut off at low resolutions

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#17]
Currently there is no sane way to represent the friendship circle when it gets too big for the screen.

Maybe make the entire thing clickable and just have it slowly rotate? Make it zoomable? Unclear what the right thing to do here is.

**Comment by randfur** [comment]
Can the circle just be scaled down to fit while the hit radius per pony be clamped to a minimum?

**Comment by blackhole12** [comment]
That would start making the ponies so small they'd barely be larger than a pixel. You might as well make the entire circle itself clickable at that point.

**Comment by NightBlader** [comment]
Perhaps give an option to disable the "news" text. That will force the other stuff to the top, right?

**Comment by DJDavid98** [comment]
Clicking ponies becomes useless in the first 10 minutes, you start getting smiles a lot faster automatically than by clicking.

**Comment by blackhole12** [comment]
For UI purposes, clicking should still be allowed even when it isn't helpful. Disabling the news only postpones the inevitable.

**Comment by DJDavid98** [comment]
Since it's already cut off, don't not try to make it not cut off, you'll just encounter more and more problems the lower the resolution. Rather, take advantage of it. Since the ponies are already organized in a circular fashion, you could use `transform: rotateZ(#deg)` along with some JavaScript to make the circle "rotatatble" by flicking/dragging, and only display 1-3 ponies at a time. This would also partially solve #6, you'd only need to throw in a hamburger menu and call it good.

**Comment by blackhole12** [comment]
Hm, I never thought about making the wheel *draggable*. That would be a great way to solve the space issue.

**Comment by blackhole12** [comment]
This was addressed in #63, although the interface itself needs refinement.
