### ISSUE TITLE
SPC on menu is based on hovering value

### ISSUE THREAD

**Issue by blackhole12** [blackhole12/PonyClicker#3]
The SPC on the menu is still displaying the incorrect value because the stat span is still being assigned it in CalcSPS().

**Comment by blackhole12** [comment]
Need to simply return SPC along with SPS in an array to preserve functions purity, then assign SPC as necessary outside of it.

**Comment by baxil** [comment]
I think part of the confusion here is that there's, for lack of a better term, a "base" SPS that SPC is calculated from with upgrades like "Ticklish Cursors" that give you a %-of-SPS bonus to SPC.  Rather than giving you a percentage of the "SPS" shown on screen (which factors in upgrades), it gives you a percentage of the base SPS.

For example, with a 1%-of- bonus to SPC upgrade and the first three "Friendship Is *" upgrades purchased (which roughly double this game's SPS from 10k to 20k), my SPC is 150.  1% of 20k is 200, so it doesn't "feel" like I'm getting a 1% bonus.

**Comment by blackhole12** [comment]
Actually, it doesn't even do that. Each upgrade applies to any upgrades that were applied before it. So, if you buy the SPC upgrade first, then it works off the base SPC upgrade, but if you buy it after the friendship upgrade, it will take that into account. It still isn't the SPS displayed on the screen, though.

I will need to figure out a better way of dealing with upgrades, presumably, but that's a different issue.
