### ISSUE TITLE
jQuery 2 vs jQuery 1

### ISSUE THREAD

**Issue by Jesin** [blackhole12/PonyClicker#40]
As far as I was able to find, the only downside of using jQuery 2 rather than jQuery 1 is that version 2 dropped support for Internet Explorer versions less than 9. CloudHop told me he has no intention of supporting those browsers anyway, so I went ahead and switched to jQuery 2. Does anybody have any objections to this?

(EDIT: In the future I'll ask the question *first*, and push to master only *after* people have had a chance to respond. Sorry ^^; )

**Comment by ngyikp** [comment]
The game is completely broken on IE8 with vanilla JS (because it doesn't support addEventListener) and jQuery 1 anyway, so upgrading jQuery would be fine ^^

Plus IE8 has no support for canvas.

![parallels picture](https://cloud.githubusercontent.com/assets/6135313/7664562/608a0108-fbc0-11e4-9831-3f2a978cfa1e.png)

I'll check on IE9 as well.

**Comment by ngyikp** [comment]
Well, it apparently breaks on the latest IE 11 too due to lack of support for ```Math.log10```:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10

It can be easily polyfilled, so I think I could try that.

![parallels picture 3](https://cloud.githubusercontent.com/assets/6135313/7664659/44e948ec-fbc4-11e4-880d-6a0530152b40.png)

**Comment by blackhole12** [comment]
By "polyfill" do you mean finding an alternative implementation of log10? I would like to support IE11 if possible.

**Comment by ngyikp** [comment]
Yeah, MDN has an alternate implementation for ```Math.log10```:
```javascript
Math.log10 = Math.log10 || function(x) {
  return Math.log(x) / Math.LN10;
};
```

Tried it and apart from the broken background canvas and animation (for some odd reason), IE11 works :)

![parallels picture 4](https://cloud.githubusercontent.com/assets/6135313/7664698/78b4a048-fbc6-11e4-866c-07d11070b2c4.png)

**Comment by blackhole12** [comment]
god what the fuck IE11. Can you commit that change for IE11?

**Comment by blackhole12** [comment]
This has all largely been addressed now.
