### ISSUE TITLE
Weird symbols in shop tooltip <ol>

### ISSUE THREAD

**Issue by DJDavid98** [blackhole12/PonyClicker#47]
![](http://i.imgur.com/zWYSUHw.png)

Visible on http://blackhole12.github.io/PonyClicker/beta/ponyclicker.html

**Comment by blackhole12** [comment]
This does not happen on my system on either chrome or firefox, but I can replicate the issue in notepad++ by interpreting the file as ASCII instead of UTF-8. It's possible the webpage isn't respecting the <meta charset> tag on some systems when loading the CSS file. I could also try to restore the actual line-list dot style but I couldn't figure out how to change the indent distance between the dot and the text.

**Comment by blackhole12** [comment]
Merged and fixed
